###############################################################
## Presence
################################################################

- id: person_logging
  alias: "Log person changes"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: person.nicholas_griffin
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: logbook.log
      data_template:
        name: "Person: "
        message: "{{trigger.to_state.name}} changed from {{trigger.from_state.state}} to {{trigger.to_state.state}} by {{ trigger.to_state.attributes.source }}"

#################################################################
## HASS Related
#################################################################

- id: battery_alert
  alias: "Battery Alert iPhone"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: sensor.ng_iphone_battery_state
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.state | length > 0 }}
  action:
    - service: persistent_notification.create
      data_template:
        title: Low Battery levels
        notification_id: low-battery-alert
        message: >
          Check battery: {{ states('sensor.battery_status') }}
