homeassistant:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 322
  name: Home
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs:
    - "/home/homeassistant/.homeassistant/downloads"
    - "/tmp"
    - "/home/homeassistant/.homeassistant/downloads/camera/"

updater:
  include_used_components: true

system_health:
zeroconf:

discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.1.10:
      name: Desk

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

arlo:
  username: !secret arlo_user
  password: !secret arlo_password

alarm_control_panel:
  - platform: arlo

mobile_app:

homekit:
  auto_start: false
  filter:
    include_entities:
      - alarm_control_panel.arlo_arlohome

downloader:
  download_dir: downloads

ffmpeg:
camera:
  - platform: arlo
    ffmpeg_arguments: "-pred 1 -q:v 2"

sun:
person:

hue:
  bridges:
    - host: 192,168..1.3
      allow_hue_groups: false
      allow_unreachable: true

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 200
    icon: mdi:home
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 200
    icon: mdi:briefcase

logger:
  default: error
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.media_player: critical
    homeassistant.components.sensor.darksky: critical
    homeassistant.core: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.http.ban: warning

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300

intent_script: !include intent_script.yaml
ios: !include ios.yaml
alert: !include alert.yaml
automation: !include automations.yaml
cover: !include cover.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
frontend: !include frontend.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
lovelace: !include lovelace.yaml
